/**
 * Resilient fallback data for Destination Countries and Published Jobs
 * Ensures the homepage, /jobs, and /countries pages ALWAYS render beautifully
 * even if the database is initializing, empty, or experiencing connection delay.
 */

export const FALLBACK_COUNTRIES = [
  {
    id: 'country-sa',
    name: 'সৌদি আরব (Saudi Arabia)',
    code: 'SA',
    flag: 'https://flagcdn.com/w40/sa.png',
    slug: 'saudi-arabia',
    continent: 'GULF',
    currency: 'সৌদি রিয়াল',
    currencyCode: 'SAR',
    recruitmentStatus: 'ACTIVE',
    description: 'NEOM ও মেগা প্রজেক্টে ভারী কনস্ট্রাকশন, হেভি ড্রাইভার, পাইপ ফিটার, ইলেকট্রিশিয়ান ও ফ্যাসিলিটি স্টাফ পদে বিশাল নিয়োগ।',
    featured: true,
    displayOrder: 1,
    isActive: true,
    jobsCount: 8,
    _count: { jobs: 8 },
  },
  {
    id: 'country-ae',
    name: 'সংযুক্ত আরব আমিরাত (UAE)',
    code: 'AE',
    flag: 'https://flagcdn.com/w40/ae.png',
    slug: 'uae',
    continent: 'GULF',
    currency: 'ইউএই দিরহাম',
    currencyCode: 'AED',
    recruitmentStatus: 'ACTIVE',
    description: 'দুবাই ও আবুধাবিতে হসপিটালিটি, মেকানিক্যাল ট্রেডস, এসি টেকনিশিয়ান, সিকিউরিটি ও লজিস্টিকসে নিয়মিত সরকারি সার্কুলার।',
    featured: true,
    displayOrder: 2,
    isActive: true,
    jobsCount: 6,
    _count: { jobs: 6 },
  },
  {
    id: 'country-qa',
    name: 'কাতার (Qatar)',
    code: 'QA',
    flag: 'https://flagcdn.com/w40/qa.png',
    slug: 'qatar',
    continent: 'GULF',
    currency: 'কাতারি রিয়াল',
    currencyCode: 'QAR',
    recruitmentStatus: 'ACTIVE',
    description: 'দোহা ইন্ডাস্ট্রিয়াল সিটি, এলএনজি গ্যাস রিফাইনারি ও এয়ারপোর্ট প্রজেক্টে সার্টিফাইড ৬জি ওয়েল্ডার ও টেকনিক্যাল পদে আকর্ষণীয় বেতন।',
    featured: true,
    displayOrder: 3,
    isActive: true,
    jobsCount: 5,
    _count: { jobs: 5 },
  },
  {
    id: 'country-kw',
    name: 'কুয়েত (Kuwait)',
    code: 'KW',
    flag: 'https://flagcdn.com/w40/kw.png',
    slug: 'kuwait',
    continent: 'GULF',
    currency: 'কুয়েতি দিনার',
    currencyCode: 'KWD',
    recruitmentStatus: 'ACTIVE',
    description: 'স্বাস্থ্যসেবা, হাসপাতাল নার্স, মেকানিক ও সরকারি কারিগরি প্রজেক্টে দীর্ঘমেয়াদী কর্মসংস্থান ও সর্বোচ্চ মুদ্রা মান।',
    featured: true,
    displayOrder: 4,
    isActive: true,
    jobsCount: 4,
    _count: { jobs: 4 },
  },
  {
    id: 'country-om',
    name: 'ওমান (Oman)',
    code: 'OM',
    flag: 'https://flagcdn.com/w40/om.png',
    slug: 'oman',
    continent: 'GULF',
    currency: 'ওমানি রিয়াল',
    currencyCode: 'OMR',
    recruitmentStatus: 'LIMITED',
    description: 'সিভিল কনস্ট্রাকশন, ফ্যাব্রিকেশন, হেভি ট্রান্সপোর্ট ও কৃষি শিল্পে অনুমোদিত কোটায় নির্বাচিত জনবল প্রেরণের সুযোগ।',
    featured: false,
    displayOrder: 5,
    isActive: true,
    jobsCount: 3,
    _count: { jobs: 3 },
  },
  {
    id: 'country-sg',
    name: 'সিঙ্গাপুর (Singapore)',
    code: 'SG',
    flag: 'https://flagcdn.com/w40/sg.png',
    slug: 'singapore',
    continent: 'ASIA',
    currency: 'সিঙ্গাপুর ডলার',
    currencyCode: 'SGD',
    recruitmentStatus: 'ACTIVE',
    description: 'বিসিএ সার্টিফাইড কনস্ট্রাকশন ও সেমবকর্প মেরিন শিপইয়ার্ডে দক্ষ কর্মীদের জন্য বিশ্বমানের কর্মপরিবেশ ও উচ্চ আয়।',
    featured: true,
    displayOrder: 6,
    isActive: true,
    jobsCount: 4,
    _count: { jobs: 4 },
  },
  {
    id: 'country-my',
    name: 'মালয়েশিয়া (Malaysia)',
    code: 'MY',
    flag: 'https://flagcdn.com/w40/my.png',
    slug: 'malaysia',
    continent: 'ASIA',
    currency: 'মালয়েশিয়ান রিঙ্গিত',
    currencyCode: 'MYR',
    recruitmentStatus: 'ACTIVE',
    description: 'সরকারি বিএমইটি কোটায় ইলেকট্রনিক্স অ্যাসেম্বলি, ফ্যাক্টরি ম্যানুফ্যাকচারিং ও বৃক্ষরোপণ শিল্পে বৈধ ভিসা অনুমোদন।',
    featured: true,
    displayOrder: 7,
    isActive: true,
    jobsCount: 5,
    _count: { jobs: 5 },
  },
  {
    id: 'country-jp',
    name: 'জাপান (Japan)',
    code: 'JP',
    flag: 'https://flagcdn.com/w40/jp.png',
    slug: 'japan',
    continent: 'ASIA',
    currency: 'জাপানিজ ইয়েন',
    currencyCode: 'JPY',
    recruitmentStatus: 'ACTIVE',
    description: 'এসএসডব্লিউ (SSW) ও টিআইটিপি প্রোগ্রামের মাধ্যমে নার্সিং, কেয়ারগিভিং ও অটোমোবাইল ফ্যাক্টরিতে স্থায়ী ক্যারিয়ার ও সুরক্ষা।',
    featured: true,
    displayOrder: 8,
    isActive: true,
    jobsCount: 3,
    _count: { jobs: 3 },
  },
  {
    id: 'country-kr',
    name: 'দক্ষিণ কোরিয়া (South Korea)',
    code: 'KR',
    flag: 'https://flagcdn.com/w40/kr.png',
    slug: 'south-korea',
    continent: 'ASIA',
    currency: 'কোরিয়ান ওন',
    currencyCode: 'KRW',
    recruitmentStatus: 'ACTIVE',
    description: 'ইপিএস (EPS) সরকারি নিয়মে ম্যানুফ্যাকচারিং ও ফিশিং ক্যাটাগরিতে চমৎকার বেতন, বিনামূল্যে আবাসন ও চিকিৎসা সুবিধা।',
    featured: false,
    displayOrder: 9,
    isActive: true,
    jobsCount: 2,
    _count: { jobs: 2 },
  },
  {
    id: 'country-ro',
    name: 'রোমানিয়া (Romania)',
    code: 'RO',
    flag: 'https://flagcdn.com/w40/ro.png',
    slug: 'romania',
    continent: 'EUROPE',
    currency: 'রোমানিয়ান লিউ',
    currencyCode: 'RON',
    recruitmentStatus: 'ACTIVE',
    description: 'ইউরোপীয় ইউনিয়ন ওয়ার্ক পারমিটে ফুড প্যাকেজিং ফ্যাক্টরি, ওয়্যারহাউস লজিস্টিকস ও হোটেল ক্যাটারিং স্টাফ সরাসরি নিয়োগ।',
    featured: true,
    displayOrder: 10,
    isActive: true,
    jobsCount: 4,
    _count: { jobs: 4 },
  },
  {
    id: 'country-pl',
    name: 'পোল্যান্ড (Poland)',
    code: 'PL',
    flag: 'https://flagcdn.com/w40/pl.png',
    slug: 'poland',
    continent: 'EUROPE',
    currency: 'পোলিশ জ্লোটি',
    currencyCode: 'PLN',
    recruitmentStatus: 'ACTIVE',
    description: 'শেনজেন জোনভুক্ত পোল্যান্ডে মেট গ্রিনহাউস ফার্মিং ও ইলেকট্রনিক্স পার্টস প্রস্তুতকারক কোম্পানিতে বৈধ চাকরির সুযোগ।',
    featured: false,
    displayOrder: 11,
    isActive: true,
    jobsCount: 3,
    _count: { jobs: 3 },
  },
  {
    id: 'country-pt',
    name: 'পর্তুগাল (Portugal)',
    code: 'PT',
    flag: 'https://flagcdn.com/w40/pt.png',
    slug: 'portugal',
    continent: 'EUROPE',
    currency: 'ইউরো',
    currencyCode: 'EUR',
    recruitmentStatus: 'ACTIVE',
    description: 'কৃষি খামার, গ্রিনহাউস হার্ভেস্টিং ও পর্যটন হোটেল সার্ভিসে বৈধ কাজের সুযোগ ও ইউরোপীয় পিআর প্রাপ্তির পথ।',
    featured: false,
    displayOrder: 12,
    isActive: true,
    jobsCount: 2,
    _count: { jobs: 2 },
  },
];

export const FALLBACK_JOBS = [
  {
    id: 'job-fb-1',
    jobCode: 'SGR-JOB-2026-001',
    title: 'হেভি ইকুইপমেন্ট ও ট্রেইলার ড্রাইভার',
    titleLocal: 'হেভি ইকুইপমেন্ট ও ট্রেইলার ড্রাইভার',
    slug: 'heavy-trailer-driver-saudi',
    countryId: 'country-sa',
    country: {
      id: 'country-sa',
      name: 'সৌদি আরব (Saudi Arabia)',
      code: 'SA',
      flag: 'https://flagcdn.com/w40/sa.png',
      slug: 'saudi-arabia',
    },
    jobCategoryId: 'cat-driving',
    jobCategory: {
      id: 'cat-driving',
      name: 'ড্রাইভিং ও লজিস্টিকস',
      slug: 'driving',
    },
    employerId: 'emp-fb-1',
    employer: {
      companyName: 'আল-বাওয়ানী কন্সট্রাকশন অ্যান্ড ইঞ্জিনিয়ারিং কো.',
    },
    description: 'সৌদি আরবের রিয়াদ ও নিওম মেগা প্রজেক্টে ট্রেইলার ও হেভি ডাম্পার চালানোর জন্য বৈধ জিসিসি বা দেশি লাইসেন্সধারী দক্ষ চালক প্রয়োজন। কোম্পানিতে বিনামূল্যে থাকা-খাওয়া ও ওভারটাইমের সুযোগ রয়েছে।',
    salaryMin: 2400,
    salaryMax: 3200,
    currency: 'SAR',
    salaryPeriod: 'MONTHLY',
    experienceRequired: 3,
    vacancyCount: 25,
    accommodation: true,
    food: true,
    transportation: true,
    medical: true,
    airTicket: true,
    workingHours: '৮ ঘণ্টা / ৬ দিন',
    contractDuration: '২ বছর (নবায়নযোগ্য)',
    status: 'PUBLISHED',
    featured: true,
    createdAt: new Date('2026-09-15'),
  },
  {
    id: 'job-fb-2',
    jobCode: 'SGR-JOB-2026-002',
    title: 'সার্টিফাইড ৬জি পাইপ ফিটার ও ওয়েল্ডার',
    titleLocal: 'সার্টিফাইড ৬জি পাইপ ফিটার ও ওয়েল্ডার',
    slug: 'certified-6g-pipe-welder-qatar',
    countryId: 'country-qa',
    country: {
      id: 'country-qa',
      name: 'কাতার (Qatar)',
      code: 'QA',
      flag: 'https://flagcdn.com/w40/qa.png',
      slug: 'qatar',
    },
    jobCategoryId: 'cat-welding',
    jobCategory: {
      id: 'cat-welding',
      name: 'ওয়েল্ডিং ও মেটাল ফেব্রিকেশন',
      slug: 'welding',
    },
    employerId: 'emp-fb-2',
    employer: {
      companyName: 'কাতোগাস ইন্ডাস্ট্রিয়াল সার্ভিসেস লিমিটেড',
    },
    description: 'কাতার এলএনজি গ্যাস রিফাইনারি সম্প্রসারণে উচ্চ চাপের গ্যাস পাইপলাইনে টিগ ও আর্ক ওয়েল্ডিংয়ে অভিজ্ঞ ৬জি সার্টিফাইড ওয়েল্ডার আবশ্যক। কোম্পানি সরকারি শ্রম আইন অনুযায়ী সম্পূর্ণ সুবিধা প্রদান করবে।',
    salaryMin: 2200,
    salaryMax: 2800,
    currency: 'QAR',
    salaryPeriod: 'MONTHLY',
    experienceRequired: 2,
    vacancyCount: 15,
    accommodation: true,
    food: true,
    transportation: true,
    medical: true,
    airTicket: true,
    workingHours: '৮ ঘণ্টা / ৬ দিন',
    contractDuration: '২ বছর (নবায়নযোগ্য)',
    status: 'PUBLISHED',
    featured: true,
    createdAt: new Date('2026-09-14'),
  },
  {
    id: 'job-fb-3',
    jobCode: 'SGR-JOB-2026-003',
    title: 'ইন্ডাস্ট্রিয়াল ইলেকট্রিশিয়ান ও টেকনিশিয়ান',
    titleLocal: 'ইন্ডাস্ট্রিয়াল ইলেকট্রিশিয়ান ও টেকনিশিয়ান',
    slug: 'industrial-electrician-uae',
    countryId: 'country-ae',
    country: {
      id: 'country-ae',
      name: 'সংযুক্ত আরব আমিরাত (UAE)',
      code: 'AE',
      flag: 'https://flagcdn.com/w40/ae.png',
      slug: 'uae',
    },
    jobCategoryId: 'cat-electrical',
    jobCategory: {
      id: 'cat-electrical',
      name: 'ইলেকট্রিক্যাল ও পাওয়ার সিস্টেম',
      slug: 'electrical',
    },
    employerId: 'emp-fb-3',
    employer: {
      companyName: 'হ্যাবটুর ইঞ্জিনিয়ারিং এলএলসি (দুবাই)',
    },
    description: 'দুবাইয়ের বাণিজ্যিক বহুতল ভবন ও শিল্প কারখানায় এইচটি/এলটি প্যানেল বোর্ড, ক্যাবল ট্রে এবং মেইনটেন্যান্স কাজের জন্য প্রশিক্ষণপ্রাপ্ত ইলেকট্রিশিয়ান প্রয়োজন। থাকা, খাওয়া ও বিমান টিকিট কোম্পানি বহন করবে।',
    salaryMin: 2600,
    salaryMax: 3400,
    currency: 'AED',
    salaryPeriod: 'MONTHLY',
    experienceRequired: 2,
    vacancyCount: 20,
    accommodation: true,
    food: true,
    transportation: true,
    medical: true,
    airTicket: true,
    workingHours: '৮ ঘণ্টা / ৬ দিন',
    contractDuration: '২ বছর (নবায়নযোগ্য)',
    status: 'PUBLISHED',
    featured: true,
    createdAt: new Date('2026-09-13'),
  },
  {
    id: 'job-fb-4',
    jobCode: 'SGR-JOB-2026-004',
    title: 'এসএসডব্লিউ কেয়ারগিভার ও নার্সিং সহকারী',
    titleLocal: 'এসএসডব্লিউ কেয়ারগিভার ও নার্সিং সহকারী',
    slug: 'ssw-caregiver-japan',
    countryId: 'country-jp',
    country: {
      id: 'country-jp',
      name: 'জাপান (Japan)',
      code: 'JP',
      flag: 'https://flagcdn.com/w40/jp.png',
      slug: 'japan',
    },
    jobCategoryId: 'cat-caregiving',
    jobCategory: {
      id: 'cat-caregiving',
      name: 'কেয়ারগিভিং ও নার্সিং',
      slug: 'caregiver',
    },
    employerId: 'emp-fb-4',
    employer: {
      companyName: 'টোকিও হেলথকেয়ার কর্পোরেশন (জাপান)',
    },
    description: 'জাপান সরকারের অনুমোদিত স্পেসিফায়েড স্কিল্ড ওয়ার্কার (SSW-1) ভিসায় প্রবীণ নিবাসে সেবাদানকারী কর্মী আবশ্যক। জাপানি ভাষা (N4/JFT) ও নার্সিং দক্ষতা পরীক্ষায় উত্তীর্ণদের সরাসরি ভিসা ও স্থায়ী হওয়ার সুযোগ।',
    salaryMin: 180000,
    salaryMax: 220000,
    currency: 'JPY',
    salaryPeriod: 'MONTHLY',
    experienceRequired: 1,
    vacancyCount: 12,
    accommodation: true,
    food: false,
    transportation: true,
    medical: true,
    airTicket: true,
    workingHours: '৮ ঘণ্টা / ৫ দিন',
    contractDuration: '৩ বছর (নবায়নযোগ্য)',
    status: 'PUBLISHED',
    featured: true,
    createdAt: new Date('2026-09-12'),
  },
  {
    id: 'job-fb-5',
    jobCode: 'SGR-JOB-2026-005',
    title: 'মেরিন শিপইয়ার্ড মেকানিক ও টেকনিশিয়ান',
    titleLocal: 'মেরিন শিপইয়ার্ড মেকানিক ও টেকনিশিয়ান',
    slug: 'shipyard-marine-technician-singapore',
    countryId: 'country-sg',
    country: {
      id: 'country-sg',
      name: 'সিঙ্গাপুর (Singapore)',
      code: 'SG',
      flag: 'https://flagcdn.com/w40/sg.png',
      slug: 'singapore',
    },
    jobCategoryId: 'cat-marine',
    jobCategory: {
      id: 'cat-marine',
      name: 'শিপবিল্ডিং ও মেরিন টেকনোলজি',
      slug: 'marine',
    },
    employerId: 'emp-fb-5',
    employer: {
      companyName: 'সেমবকর্প মেরিন সিঙ্গাপুর',
    },
    description: 'সিঙ্গাপুর জুড়ং শিপইয়ার্ডে বাণিজ্যিক জাহাজের ইঞ্জিন মেরামত, ডকিং ও মেকানিক্যাল ফিটিং কাজে দক্ষ কারিগর আবশ্যক। সিঙ্গাপুর সরকারের নিয়মে ওটি এবং আকর্ষণীয় বোনাস প্রযোজ্য।',
    salaryMin: 1400,
    salaryMax: 1900,
    currency: 'SGD',
    salaryPeriod: 'MONTHLY',
    experienceRequired: 2,
    vacancyCount: 18,
    accommodation: true,
    food: true,
    transportation: true,
    medical: true,
    airTicket: true,
    workingHours: '৮ ঘণ্টা / ৬ দিন',
    contractDuration: '২ বছর (নবায়নযোগ্য)',
    status: 'PUBLISHED',
    featured: false,
    createdAt: new Date('2026-09-10'),
  },
  {
    id: 'job-fb-6',
    jobCode: 'SGR-JOB-2026-006',
    title: 'ফুড প্রসেসিং ও ফ্যাক্টরি প্যাকেজিং স্টাফ',
    titleLocal: 'ফুড প্রসেসিং ও ফ্যাক্টরি প্যাকেজিং স্টাফ',
    slug: 'factory-food-packaging-romania',
    countryId: 'country-ro',
    country: {
      id: 'country-ro',
      name: 'রোমানিয়া (Romania)',
      code: 'RO',
      flag: 'https://flagcdn.com/w40/ro.png',
      slug: 'romania',
    },
    jobCategoryId: 'cat-manufacturing',
    jobCategory: {
      id: 'cat-manufacturing',
      name: 'ম্যানুফ্যাকচারিং ও ফ্যাক্টরি প্রোডাকশন',
      slug: 'manufacturing',
    },
    employerId: 'emp-fb-6',
    employer: {
      companyName: 'ট্রান্সিলভানিয়া লজিস্টিকস এসআরএল',
    },
    description: 'ইউরোপীয় ইউনিয়নভুক্ত রোমানিয়ার আধুনিক খাদ্য প্রক্রিয়াকরণ কারখানায় স্বয়ংক্রিয় মেশিনে পণ্য প্যাকেজিং ও স্টোরেজ কাজের জন্য পুরুষ ও মহিলা কর্মী আবশ্যক। ইউরোপীয় মানদণ্ডে আবাসন ও হেলথ ইন্সুরেন্স নিশ্চিত।',
    salaryMin: 3400,
    salaryMax: 4200,
    currency: 'RON',
    salaryPeriod: 'MONTHLY',
    experienceRequired: 0,
    vacancyCount: 30,
    accommodation: true,
    food: true,
    transportation: true,
    medical: true,
    airTicket: true,
    workingHours: '৮ ঘণ্টা / ৫ দিন',
    contractDuration: '২ বছর (নবায়নযোগ্য)',
    status: 'PUBLISHED',
    featured: false,
    createdAt: new Date('2026-09-08'),
  },
];
